### ISSUE TITLE
ModuleNotFoundError: No module named 'jiplib'

### ISSUE THREAD

**Issue by kokkytos** [ec-jrc/jeolib-jiplib#1]
I successfully build and install jiplib.

But when I'm importing (`import pyjeo`) in python I get the error:

```python

>>> import pyjeo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/leonidas/miniconda3/envs/gee/lib/python3.10/site-packages/pyjeo/__init__.py", line 22, in <module>
    from .pyjeo import *
  File "/home/leonidas/miniconda3/envs/gee/lib/python3.10/site-packages/pyjeo/pyjeo.py", line 41, in <module>
    import jiplib as _jl
ModuleNotFoundError: No module named 'jiplib'

```
I attach the [CMakeOutput.log](https://github.com/user-attachments/files/17538904/CMakeOutput.log)

**Comment by kempenep** [comment]
Can you confirm all steps explained [here](https://github.com/ec-jrc/jeolib-jiplib#install-dependency-libraries-example-for-debian-based-system-using-apt) were performed successfully? That is miallib was also compiled and installed first? Could you please attach the output of the following commands in your build directory of jiplib?
1)  `cmake ..` you executed in the build directory
2) `cmake --build .`

**Comment by kempenep** [comment]
I am not very much into conda environments, but I suspect this might be the issue. The jiplib dynamic library (so file) has apparently been installed and so was the jiplib python package. I am wondering where the package was installed in the system as there might be a conflict between the system and conda environment (there were also the WARNING messages on "invalid distribution"). 
When you launch python from the build directory, it finds the jiplib package in the current path. The fact that it is not found when you are not in the build directory, tells me the library was probably not properly installed in the environment you are working in (conda). Is jiplib listed as part of the packages installed (and is pyjeo)?

**Comment by kokkytos** [comment]
*miallib* and *jiplib* are not listed in the installed packages. 

But *pyjeo* is listed

**Comment by kempenep** [comment]
Just to make sure I understand. You are already within the conda environment while performing all cmake commands. Question is why `pip install` of the jiplib wheel did not install correctly within the conda environment. Although it is not [recommended](https://docs.conda.io/projects/conda-build/en/latest/user-guide/wheel-files.html), I believe it should work to install a wheel within a conda env with pip. What happens if you manually install the jiplib wheel with `pip install` on the command line (not as part of the cmake install script), also within your conda env? Does it list jiplib then as part of the installed conda packages?

This should not be different than what you did with the pyjeo wheel I believe, i.e., you also installed with a `pip install` pyjeo wheel, correct? 

nb: it is normal that miallib is not installed as a python package. We only need the dynamic library here.

**Comment by kokkytos** [comment]
I re run cmake commands (my conda env activated) and install it manually using `pip install`

Now it works.

**Comment by kempenep** [comment]
Great, I suppose now both jiplib and pyjeo are installed in the conda env as you can check it with `conda list`? To make sure all works fine, did you try to run the [test suite](https://github.com/ec-jrc/jeolib-pyjeo#test-the-installation)?

**Comment by kokkytos** [comment]
Yes the two packages are listed in `conda list`.

This is the result of the test `python -W ignore -m unittest -v tests`:

```bash
$ python -W ignore -m unittest -v tests
test_colorsys (tests.test_ccops.BadCCOps)
Test color system conversions. ... ok
test_distances (tests.test_ccops.BadCCOps)
Test the distance functions and methods. ... ok
test_labelling (tests.test_ccops.BadCCOps)
Test the labelling functions and methods. ... ok
test_sml (tests.test_classify.BadClassify)
Test the Symbolic Machine Learning classifier. ... ok
test_catchments (tests.test_demops.BadDEMOps)
Test catchment basin funcs and methods. ... ok
test_drainage_areas (tests.test_demops.BadDEMOps)
Test drainage area functions and methods. ... ok
test_flood_dir (tests.test_demops.BadDEMOps)
Test floodDir() func and method. ... ok
test_flows (tests.test_demops.BadDEMOps)
Test DEM flow functions and methods. ... ok
test_hillShade (tests.test_demops.BadDEMOps)
Test hillShade functions and methods. ... ok
test_pit_removals (tests.test_demops.BadDEMOps)
Test functions and methods for pit removals. ... ok
test_slope (tests.test_demops.BadDEMOps)
Test DEM flow functions and methods. ... ok
test_slopes (tests.test_demops.BadDEMOps)
Test demSlopeD8() function and method. ... ok
test_strahler (tests.test_demops.BadDEMOps)
Test function and method for Strahler order. ... ok
test_band2plane (tests.test_geometry.BadGeometry)
Test the band2plane method. ... ok
test_band2plane_dimension (tests.test_geometry.BadGeometry) ... ok
test_coords_transformations (tests.test_geometry.BadGeometry)
Test geo2image() and image2geo() functions and methods. ... ok
test_covers (tests.test_geometry.BadGeometry)
Test the covers method. ... ok
test_crop (tests.test_geometry.BadGeometry)
Test crop...() functions and methods. ... ok
test_extract_allpoints (tests.test_geometry.BadGeometry)
Test the extract method for allpoints. ... ok
test_extract_allpoints_name (tests.test_geometry.BadGeometry)
Test the extract method for allpoints name. ... ok
test_extract_band_plane (tests.test_geometry.BadGeometry)
Test the extract method for multiband multiplanes. ... reading layer geometry
ok
test_extract_band_plane_name (tests.test_geometry.BadGeometry)
Test the extract method for multiband multiplanes names. ... reading layer geometry
ok
test_extract_image (tests.test_geometry.BadGeometry)
Test the extract method for thematic reference. ... ok
test_extract_image_name (tests.test_geometry.BadGeometry)
Test the extract method for thematic reference name. ... ok
test_extract_loop (tests.test_geometry.BadGeometry)
Test the extract method looping over bands using join function. ... reading layer geometry
reading layer geometry
reading layer geometry
reading layer geometry
reading layer geometry
reading layer geometry
reading layer geometry
reading layer geometry
reading layer geometry
reading layer geometry
reading layer geometry
reading layer geometry
ok
test_extract_multiband (tests.test_geometry.BadGeometry)
Test the extractOgr method for jim with multibands. ... reading layer geometry
reading layer geometry
ok
test_extract_multiband_name (tests.test_geometry.BadGeometry)
Test the extractOgr method for jim with multibands with names. ... reading layer geometry
reading layer geometry
ok
test_extract_plane (tests.test_geometry.BadGeometry)
Test the extractOgr method for multiplanes. ... reading layer geometry
ok
test_extract_plane_name (tests.test_geometry.BadGeometry)
Test the extractOgr method for multiplanes names. ... reading layer geometry
ok
test_extract_warp (tests.test_geometry.BadGeometry)
Test the extract method for multiband multiplanes names. ... Error: spatial reference of vector sample must be identical to raster

reading layer geometry
12
ok
test_image_frames (tests.test_geometry.BadGeometry)
Test imageFrame...() functions and methods. ... ok
test_plotLine (tests.test_geometry.BadGeometry)
Test the plotLine() function and method. ... ok
test_polygonize (tests.test_geometry.BadGeometry)
Test the polygonize() function and method. ... ok
test_rasterize (tests.test_geometry.BadGeometry)
Test the rasterize() function and method for bytes. ... ok
test_reducePlane (tests.test_geometry.BadGeometry)
Test the reducePlane() function and method. ... ok
test_repeat (tests.test_geometry.BadGeometry)
Test the repeat() function and method. ... ok
test_stack (tests.test_geometry.BadGeometry)
Test the stackBand and stackPlane methods. ... ok
test_stack_dimension (tests.test_geometry.BadGeometry)
Test the stackBand and stackPlane methods. ... ok
test_warp (tests.test_geometry.BadGeometry)
Test the warp method. ... ok
test_warp_jimvect (tests.test_geometry.BadGeometry)
Test the warp method and function for JimVect. ... ok
test_stack (tests.test_geometry.BadGeometryLists)
Test the stackBand and stackPlane methods. ... ok
test_append (tests.test_geometry.BadGeometryVects)
Test the append methods. ... ERROR 1: sqlite3_step() failed:
  UNIQUE constraint failed: milano.ogc_fid (19)
ERROR 1: sqlite3_step() failed:
  UNIQUE constraint failed: milano.ogc_fid (19)
ok
test_convexhull (tests.test_geometry.BadGeometryVects)
Test the convexHull() function and method. ... ok
test_intersect (tests.test_geometry.BadGeometryVects)
Test the stack band method. ... ok
test_join (tests.test_geometry.BadGeometryVects)
Test the join() function and method. ... reading layer geometry
reading layer geometry
ok
test_sample (tests.test_geometry.BadGeometryVects)
Test the sample function. ... Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
ok
test_close (tests.test_io.BadIO)
Test closing Jim objects. ... ok
test_write (tests.test_io.BadIOVects)
Test writing JimVect objects. ... ok
test_write_co (tests.test_io.BadIOVects) ... ok
test_write_nc (tests.test_io.BadIOVects) ... ok
test_write_tif (tests.test_io.BadIOVects) ... ok
test_args_different_formats (tests.test_jim_basics.BadBasicMethods)
Test the parsing of arguments as bytes, unicode, etc. ... ok
test_checks (tests.test_jim_basics.BadBasicMethods)
Test checks of arguments appearing behind the scene. ... ok
test_getters_setters (tests.test_jim_basics.BadBasicMethods)
Test getters and setters. ... ok
test_jim_creations (tests.test_jim_basics.BadBasicMethods)
Test creating of Jim objects. ... /home/leonidas/Desktop/pyjeo/jeolib-pyjeo/pyjeo/pyjeo.py:67: SyntaxWarning: Not possible to create Jim image based on another one together with other kwargs than copy_data. kwargs ignored.
  _warnings.warn(

ok
test_numpy_conversions (tests.test_jim_basics.BadBasicMethods)
Test conversions to numpy and back. ... ok
test_operators (tests.test_jim_basics.BadBasicMethods)
Test basic operators (+, -, *, /, =, abs(), ~). ... ok
test_pixel_wise_conditions (tests.test_jim_basics.BadBasicMethods)
Test conditions like ==, !=, >, >=, <, <= for Jims. ... ok
test_xr (tests.test_jim_basics.BadBasicMethods)
Test the parsing of arguments as bytes, unicode, etc. ... ok
test_jimlist_creations (tests.test_jimlist_basics.BadBasicMethodLists)
Test different ways to create JimList. ... ok
test_list_methods (tests.test_jimlist_basics.BadBasicMethodLists)
Test basic methods originating in list() inheritance. ... ok
test_dict_conversions (tests.test_jimvect_basics.BadBasicMethods)
Test JimVect.np() method. ... ok
test_jimvect_creations (tests.test_jimvect_basics.BadBasicMethods)
Test creating of JimVect objects. ... field and label types can be:  Integer IntegerList Real RealList String StringList (unknown) (unknown) Binary Date Time
field type is: Real
spatial reference of vector target is same as raster
ERROR 6: Update from inline definition not supported
ERROR 6: Update from inline definition not supported
ok
test_numpy_conversions (tests.test_jimvect_basics.BadBasicMethods)
Test JimVect.np() method. ... ok
test_dwt (tests.test_ngbops.BadNgbOps)
Test dwt() and dwti() functions and methods. ... ok
test_edgeWeight (tests.test_ngbops.BadNgbOps)
Test edgeWeight() function and method. ... ok
test_erode_dilate (tests.test_ngbops.BadNgbOps)
Test morphoDilate... and morphoErode...() functions and methods. ... ok
test_filters (tests.test_ngbops.BadNgbOps)
Test filter1d() and filter2d() functions and methods. ... ok
test_getDissim (tests.test_ngbops.BadNgbOps)
Test getDissim() function and method. ... ok
test_smoothNoData1d (tests.test_ngbops.BadNgbOps)
Test smoothNoData1d functions and methods. ... ok
test_NDVI (tests.test_pixops.BadPixOps)
Test computing NDVI in different ways. ... /home/leonidas/Desktop/pyjeo/jeolib-pyjeo/pyjeo/modules/pixops.py:191: RuntimeWarning: invalid value encountered in divide
  ndvi = (nirnp - rednp) / (rednp + nirnp)
/home/leonidas/Desktop/pyjeo/jeolib-pyjeo/pyjeo/modules/pixops.py:583: RuntimeWarning: invalid value encountered in divide
  ndvi = (nirnp - rednp) / (rednp + nirnp)
WARNING in generic_ndi(im1, im2):              70192 division(s) by 0 set to -2)

WARNING in generic_ndi(im1, im2):              70192 division(s) by 0 set to -2)

ok
test_NDVI_dimension (tests.test_pixops.BadPixOps)
Test computing NDVI in different ways. ... WARNING in generic_ndi(im1, im2):              70192 division(s) by 0 set to -2)

WARNING in generic_ndi(im1, im2):              70192 division(s) by 0 set to -2)

ok
test_convert (tests.test_pixops.BadPixOps)
Test data type conversions. ... ok
test_histoCompress (tests.test_pixops.BadPixOps)
Test histoCompress() function and method. ... ok
test_setFunctions (tests.test_pixops.BadPixOps)
Test setData, setLevel and setThreshold functions and methods. ... ok
test_simple_op (tests.test_pixops.BadPixOps)
Test simpleArithOp() and simpleBitwiseOp() functions and methods. ... ok
test_stretch (tests.test_pixops.BadPixOps)
Test stretch function. ... ok
test_supremum_infimum (tests.test_pixops.BadPixOps)
Test picking up supremum and infimum from computed NDVIs. ... ok
test_bbox (tests.test_properties.BadProps)
Test getBBox() method. ... ok
test_covers (tests.test_properties.BadProps)
Test covers() method. ... ok
test_geo_transform (tests.test_properties.BadProps)
Test GeoTransform() methods. ... ok
test_georeference (tests.test_properties.BadProps)
Test georeference (projection + geotransform) methods. ... ok
test_isEqual (tests.test_properties.BadProps)
Test isEqual() method. ... ok
test_no_data_vals (tests.test_properties.BadProps)
Test functions connected to no data values. ... ok
test_projection (tests.test_properties.BadProps)
Test Projection() methods. ... ok
test_refpix (tests.test_properties.BadProps)
Test getRefPix() method. ... ok
test_bbox (tests.test_properties.BadPropsLists)
Test JimList properties.getBBox() method. ... ok
test_covers (tests.test_properties.BadPropsLists)
Test JimList properties.covers() method. ... ok
test_no_data_vals (tests.test_properties.BadPropsLists)
Test JimList methods connected to no data values. ... ok
test_selectGeo (tests.test_properties.BadPropsLists)
Test JimList properties.selectGeo() function and method. ... ok
test_feature_layer_counts (tests.test_properties.BadPropsVects)
Test JimVect methods getLayerCount() and getFeatureType(). ... ok
test_geospatial_infos (tests.test_properties.BadPropsVects)
Test JimVect methods connected to geospatial informations. ... ok
test_isEqual (tests.test_properties.BadPropsVects)
Test JimVect isEqual method. ... ERROR 1: sqlite3_step() failed:
  UNIQUE constraint failed: milano.ogc_fid (19)
ok
test_getStatProfile (tests.test_stats.BadStats)
Test if values from getStatProfile are not wrong. ... ok
test_getStats (tests.test_stats.BadStats)
Test if values from getStats are not suspicious. ... 



ok
test_histograms (tests.test_stats.BadStats)
Test that values of histograms are not suspicious. ... ok
test_stretch (tests.test_stats.BadStats)
Test stretching a Jim object. ... ok
test_getStatProfile (tests.test_stats.BadStatsLists)
Test if values from getStatProfile are not wrong. ... ok
test_getStats (tests.test_stats.BadStatsLists)
Test if values from getStats are not suspicious. ... 





ok

----------------------------------------------------------------------
Ran 99 tests in 2150.656s

OK

```

**Comment by kempenep** [comment]
Perfect, it seems all tests passed. I will close the issue then. Thanks.
